# Generated by Django 5.1.3 on 2024-12-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouquet_id', models.IntegerField(verbose_name='ID Букета')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('telephone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('comments', models.CharField(max_length=100, verbose_name='Пожелания к заказу')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='bouquets',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
    ]
