# Generated by Django 5.1.3 on 2024-12-15 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_orders_options_alter_bouquets_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquets',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
