# Generated by Django 5.1.3 on 2024-12-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='bouquet_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='bouquets',
            field=models.ManyToManyField(related_name='orders', to='main.bouquets', verbose_name='Букеты'),
        ),
    ]
